// Generated by tools/build-ui-sdk.mjs
(() => {
// Optional framework-free client for sandboxed Gamer panels. No parent DOM access.
function connectGamer({ timeout = 15000 } = {}) {
  let port, serial = 0, disposed = false
  const pending = new Map()
  let resolveReady, rejectReady
  const ready = new Promise((resolve, reject) => { resolveReady = resolve; rejectReady = reject })
  const timer = setTimeout(() => rejectReady(new Error('宿主连接超时')), timeout)
  function onConnect(event) {
    if (disposed || port || event.source !== window.parent || event.data?.type !== 'gamer-ui:connect' || event.data.version !== 'gamer-ui@1' || !event.ports[0]) return
    port = event.ports[0]
    port.onmessage = ({ data }) => {
      if (data?.type !== 'gamer-ui:response' || data.version !== 'gamer-ui@1') return
      const request = pending.get(data.id)
      if (!request) return
      pending.delete(data.id); clearTimeout(request.timer)
      if (data.ok) request.resolve(data.result)
      else request.reject(Object.assign(new Error(data.error?.message || '请求失败'), { code: data.error?.code }))
    }
    port.start(); clearTimeout(timer); resolveReady()
  }
  window.addEventListener('message', onConnect)
  async function call(method, params) {
    await ready
    if (disposed) throw new Error('面板已关闭')
    const id = String(++serial)
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => { pending.delete(id); reject(new Error('请求超时')) }, timeout)
      pending.set(id, { resolve, reject, timer })
      port.postMessage({ type: 'gamer-ui:request', version: 'gamer-ui@1', id, method, params })
    })
  }
  function dispose() {
    disposed = true; clearTimeout(timer); rejectReady(new Error('面板已关闭'))
    window.removeEventListener('message', onConnect); port?.close()
    for (const request of pending.values()) { clearTimeout(request.timer); request.reject(new Error('面板已关闭')) }
    pending.clear()
  }
  return { call, dispose, ready }
}

function applyGamerTheme(theme, root = document.documentElement) {
  const colors = { background: 'surface', field: 'field', text: 'text', secondaryText: 'muted', border: 'border', accent: 'accent' }
  for (const [key, token] of Object.entries(colors)) {
    if (/^#[\da-f]{6}$/i.test(theme?.[key] || '')) root.style.setProperty(`--gamer-${token}`, theme[key])
  }
}

window.GamerUI = Object.freeze({ connectGamer, applyGamerTheme });
})();
