<template>
  <div class="panel-sec">
    <div class="dev-pick"><select v-model="ctx.store.deviceId" class="select mono dev-select" @change="ctx.onDeviceSelect"><option value="">选择设备…</option><option v-for="d in ctx.devices" :key="d.id" :value="d.id">{{ d.name }} · {{ d.status === 'online' ? '在线' : '离线' }}</option></select><button class="btn btn-sm" :disabled="ctx.scanning" @click="ctx.refreshDevices">🔄 刷新</button><button class="btn btn-sm" @click="ctx.startAdd">＋ 新增</button></div>
    <div v-if="ctx.mode === 'add'" class="cfg-form"><div class="cfg-form-head"><span>新增设备</span><span class="cfg-form-sub">填写信息后确认添加</span></div><div class="form-item"><label>设备名称</label><input v-model="ctx.form.name" class="input" placeholder="例如：红米 Note12 挂机号" /></div><div class="form-item"><label>接入方式</label><div class="type-picker"><div v-for="t in ctx.types" :key="t.key" class="type-opt" :class="{ sel: ctx.form.kind === t.key }" @click="ctx.form.kind = t.key"><span class="type-icon">{{ t.icon }}</span><span>{{ t.label }}</span></div></div></div><div class="form-item"><label>ADB 地址 <span class="muted">（redroid / 无线 adb / 模拟器需要填写）</span></label><input v-model="ctx.form.addr" class="input mono" placeholder="redroid:5555 或 192.168.1.88:5555" /></div><div class="form-item"><label>屏幕模式</label><div class="mode-picker"><div class="mode-opt" :class="{ sel: ctx.form.screen_mode === 'mirror' }" @click="ctx.form.screen_mode = 'mirror'"><div class="mode-title">🖥️ 镜像主屏</div><div class="mode-desc">投屏设备物理屏幕，各设备分辨率不同</div></div><div class="mode-opt" :class="{ sel: ctx.form.screen_mode === 'virtual' }" @click="ctx.form.screen_mode = 'virtual'"><div class="mode-title">🖥️ 虚拟屏</div><div class="mode-desc">统一分辨率虚拟屏幕，模板跨设备通用</div></div></div></div><DeviceVirtualFields v-if="ctx.form.screen_mode === 'virtual'" :ctx="ctx" /><div class="cfg-actions"><button class="btn btn-primary" :disabled="ctx.configApplying" @click="ctx.addDevice">{{ ctx.configApplying ? '添加中…' : '确认添加' }}</button><button class="btn btn-sm" @click="ctx.cancelAdd">取消</button></div></div>
    <template v-else><div v-if="ctx.current" class="dev-summary"><ConsoleDeviceSummary :device="ctx.current" :connected="ctx.connected" :kind-icon="ctx.kindInfo(ctx.current.kind).icon" :kind-label="ctx.kindInfo(ctx.current.kind).label" :screen-summary="ctx.screenSummary" /><div class="sum-actions"><button v-if="!ctx.connected" class="btn btn-primary" :disabled="!ctx.store.deviceId || ctx.connecting" @click="ctx.flushAndConnect">{{ ctx.connecting ? '连接中…' : '🔌 连接' }}</button><button v-else class="btn" @click="ctx.disconnect">断开连接</button><button class="btn btn-danger" @click="ctx.removeDevice">删除</button></div><div class="cfg-form"><div class="cfg-form-head"><span>设备配置</span><span class="cfg-form-sub">{{ ctx.configApplying ? '保存中…' : (ctx.formDirty ? '有未保存的修改（自动保存）' : (ctx.savedVisible ? '已自动保存' : '')) }}</span></div><div class="form-item"><label>设备名称</label><input v-model="ctx.form.name" class="input" placeholder="例如：红米 Note12 挂机号" /></div><div class="form-item"><label>屏幕模式</label><div class="mode-picker"><div class="mode-opt" :class="{ sel: ctx.form.screen_mode === 'mirror' }" @click="ctx.form.screen_mode = 'mirror'"><div class="mode-title">🖥️ 镜像主屏</div><div class="mode-desc">投屏设备物理屏幕，各设备分辨率不同</div></div><div class="mode-opt" :class="{ sel: ctx.form.screen_mode === 'virtual' }" @click="ctx.form.screen_mode = 'virtual'"><div class="mode-title">🖥️ 虚拟屏</div><div class="mode-desc">统一分辨率虚拟屏幕，模板跨设备通用</div></div></div></div><DeviceVirtualFields v-if="ctx.form.screen_mode === 'virtual'" :ctx="ctx" /></div><div class="cfg-hint">{{ ctx.connected ? '已连接：修改自动保存并实时生效（自动重连）' : '未连接：修改自动保存，连接后按新配置生效' }}</div></div><div v-else class="dev-empty"><div class="dev-empty-icon">📴</div><div class="dev-empty-text">未选择设备</div><button class="btn btn-sm" @click="ctx.startAdd">＋ 新增设备</button></div></template>
  </div>
</template>
<script setup>
import { reactive } from 'vue'
import ConsoleDeviceSummary from '../ConsoleDeviceSummary.vue'
import DeviceVirtualFields from './DeviceVirtualFields.vue'
const props = defineProps({ context: { type: Object, required: true } })
const ctx = reactive(props.context)
</script>
<style scoped>
.panel-sec{background:var(--bg-1);border:1px solid var(--border);border-radius:var(--radius);padding:14px;display:flex;flex-direction:column;gap:10px}.dev-pick{display:flex;gap:6px;align-items:center}.dev-pick .dev-select{flex:1;min-width:0;padding:5px 8px;font-size:12px}.cfg-form{display:flex;flex-direction:column;gap:10px}.cfg-form-head{display:flex;align-items:baseline;justify-content:space-between;font-size:12px;font-weight:600;padding-bottom:2px;border-bottom:1px solid var(--border)}.cfg-form-sub{font-size:10px;font-weight:400;color:var(--text-2)}.cfg-actions{display:flex;gap:8px}.cfg-actions .btn-primary{flex:1}.cfg-hint{font-size:10px;color:var(--text-2)}.dev-summary{display:flex;flex-direction:column;gap:8px}.sum-actions{display:flex;align-items:center;gap:8px}.sum-actions .btn{flex:1}.sum-actions .btn-danger{flex:0 0 auto}.dev-empty{display:flex;flex-direction:column;align-items:center;gap:8px;padding:24px 0;text-align:center}.dev-empty-icon{font-size:34px;opacity:.5}.dev-empty-text{color:var(--text-2);font-size:12px}.muted{color:var(--text-2);font-weight:400}.type-picker{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.type-opt{display:flex;flex-direction:column;align-items:center;gap:5px;padding:10px 4px;border-radius:var(--radius-sm);border:1px solid var(--border);cursor:pointer;font-size:11px;color:var(--text-1)}.type-opt.sel{border-color:var(--accent);color:var(--accent);background:rgba(34,211,165,.06)}.type-icon{font-size:18px}.mode-picker{display:grid;grid-template-columns:1fr 1fr;gap:6px}.mode-opt{padding:10px;border-radius:var(--radius-sm);border:1px solid var(--border);cursor:pointer;display:flex;flex-direction:column;gap:3px}.mode-opt.sel{border-color:var(--accent);background:rgba(34,211,165,.06)}.mode-title{font-size:12px;font-weight:600}.mode-desc{font-size:10px;color:var(--text-2)}
</style>
