<template>
    <div class="form-item"><label>虚拟屏分辨率</label><div class="vd-presets"><div v-for="p in ctx.vdPresets" :key="p.res" class="vd-opt" :class="{ sel: ctx.form.vd_res === p.res && String(ctx.form.vd_dpi) === String(p.dpi) }" @click="ctx.form.vd_res = p.res; ctx.form.vd_dpi = p.dpi"><span class="vd-res mono">{{ p.res }}</span><span class="vd-dpi">@{{ p.dpi }}dpi</span></div></div></div>
    <div class="form-row"><div class="form-item"><label>宽 × 高</label><input v-model="ctx.form.vd_res" class="input mono" placeholder="1920x1080" /></div><div class="form-item"><label>DPI <span class="muted">（0=自动）</span></label><div class="dpi-box"><input v-model.number="ctx.form.vd_dpi" class="input mono" type="number" placeholder="0" /><button class="btn btn-sm" :class="{ active: !ctx.form.vd_dpi }" @click="ctx.form.vd_dpi = 0">自动</button></div></div></div>
    <div class="form-item"><label>应用 <span class="muted">（可选，连接成功后自动启动到虚拟屏）</span></label><div class="app-box"><input v-model="ctx.pkgDraft" class="input mono" placeholder="搜索应用或输入包名…（点击下拉选择，回车确认）" @focus="ctx.appOpen = true" @input="ctx.appOpen = true" @keydown.enter="ctx.commitPkg" @blur="ctx.appOpen = false" /><button class="btn btn-sm" :disabled="ctx.appLoading" @click="ctx.loadApps">{{ ctx.appLoading ? '加载中…' : '🔄 读取应用' }}</button><div class="app-menu" v-if="ctx.appOpen && ctx.appFiltered.length"><div v-for="a in ctx.appFiltered" :key="a.pkg" class="app-opt" @mousedown.prevent="ctx.pickApp(a)"><span class="app-label">{{ a.label }}</span><span class="app-pkg mono">{{ a.pkg }}</span></div></div></div><div class="muted small" v-if="ctx.appHint">{{ ctx.appHint }}</div></div>
    <div class="form-item"><label>视频帧率 <span class="muted">（scrcpy 帧率上限：越高越流畅、越耗性能）</span></label><div class="fps-presets"><div v-for="f in ctx.fpsPresets" :key="f" class="fps-opt mono" :class="{ sel: ctx.form.fps === f }" @click="ctx.form.fps = f">{{ f }}</div></div></div>
</template>
<script setup>
import { reactive } from 'vue'
const props = defineProps({ ctx: { type: Object, required: true } })
const ctx = reactive(props.ctx)
</script>
<style scoped>
.form-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.form-row .form-item{min-width:0}.dpi-box{display:flex;gap:6px}.dpi-box .input{flex:1;min-width:0}.dpi-box .btn{flex-shrink:0}.dpi-box .btn.active{border-color:var(--accent-2);color:var(--accent-2)}.muted{color:var(--text-2);font-weight:400}.small{font-size:11px;margin-top:4px}.vd-presets{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.vd-opt{display:flex;flex-direction:column;align-items:center;gap:2px;padding:8px 2px;border-radius:var(--radius-sm);border:1px solid var(--border);cursor:pointer}.vd-opt.sel{border-color:var(--accent-2);background:rgba(56,189,248,.06)}.vd-res{font-size:11px;color:var(--text-0)}.vd-dpi{font-size:10px;color:var(--text-2)}.app-box{position:relative;display:flex;gap:6px}.app-box .btn{flex-shrink:0}.app-box .input{flex:1;min-width:0}.app-menu{position:absolute;left:0;right:0;top:calc(100% + 4px);z-index:30;background:var(--bg-1);border:1px solid var(--border);border-radius:var(--radius-sm);max-height:200px;overflow:auto}.app-opt{display:flex;flex-direction:column;gap:2px;padding:7px 10px;cursor:pointer}.app-label{font-size:12px;color:var(--text-0)}.app-pkg{font-size:10px;color:var(--text-2)}.fps-presets{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.fps-opt{text-align:center;padding:8px 4px;border-radius:var(--radius-sm);border:1px solid var(--border);cursor:pointer;font-size:12px}.fps-opt.sel{border-color:var(--accent-2);color:var(--accent-2)}.mono{font-family:var(--mono);font-size:11px;color:var(--text-1)}
</style>
