// Keep the classic-script build identical to the optional ES module source.
import { readFile, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
const source = await readFile(new URL('../sdk/ui/gamer-ui.js', import.meta.url), 'utf8')
await writeFile(new URL('../sdk/ui/gamer-ui.global.js', import.meta.url), `// Generated by tools/build-ui-sdk.mjs\n(() => {\n${source.replace(/^export /gm, '')}\nwindow.GamerUI = Object.freeze({ connectGamer, applyGamerTheme });\n})();\n`)
// Opaque sandbox subresources cannot rely on SameSite session cookies. Ship one
// authenticated HTML response with hash-authorized assets, without widening CSP.
const root = new URL('../sdk/ui/', import.meta.url)
const read = async name => (await readFile(new URL(name, root), 'utf8')).replace(/\r\n/g, '\n')
const script = (await read('gamer-ui.global.js')) + '\n' + (await read('example.js'))
const css = await read('gamer-ui.css')
const hash = value => `'sha256-${createHash('sha256').update(value).digest('base64')}'`
let html = await read('example.template.html')
html = html.replace("script-src 'self'", `script-src ${hash(script)}`).replace("style-src 'self'", `style-src ${hash(css)}`)
html = html.replace('<link rel="stylesheet" href="./gamer-ui.css">', `<style>${css}</style>`)
html = html.replace('<script defer src="./gamer-ui.global.js"></script><script defer src="./example.js"></script>', '')
html = html.replace('</body>', `<script>${script}</script></body>`)
await writeFile(new URL('example.html', root), html)
